config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  mount ActionCable.server => '/cable'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: 'auth_at_provider'

  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  resources :contacts, only: %i[new create] do
    collection do
      post 'confirm', to: 'contacts#confirm', as: 'confirm'
      post 'back', to: 'contacts#back', as: 'back'
      get 'done', to: 'contacts#done', as: 'done'
    end
  end

  resources :users, only: %i[new create] do
    member do
      get 'favorites'
      get 'follows', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
    resource :relationships, only: %i[create destroy]
  end

  resources :items do
    resources :comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    get 'trashed', on: :member, to: 'items#trashed_items'
    get 'stay', on: :member, to: 'items#stay_items'
    get 'worry', on: :member, to: 'items#worry_items'
    get 'all', on: :collection, to: 'items#all_items'

    get 'search_tag', to: 'items#search_tag'
    get 'search_genre', to: 'items#search_genre'
    collection do
      get 'search', to: 'items#search', as: :search
    end
    get 'autocomplete', on: :collection, to: 'items#autocomplete'
    get 'private_item_list', on: :collection, to: 'items#private_items'
  end

  namespace :mypage do
    resource :profile, only: %i[show edit update]
    resources :profile_shows, only: %i[show]
  end

  resources :notifications, only: %i[index]

  resources :chat_rooms, only: %i[show create] do
    collection do
      get 'entrance', to: 'chat_rooms#entrance'
    end
  end

  resources :genres, only: %i[new index create]

  resources :password_resets, only: %i[new create edit update]

  get '*path', to: 'application#render404'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/mypage/base_controller.rb
class Mypage::BaseController < ApplicationController
  layout 'mypage/layouts/application'
  before_action :require_login
end

app/controllers/mypage/profile_shows_controller.rb
class Mypage::ProfileShowsController < Mypage::BaseController
  def show
    @user = User.find(params[:id])
    @following_users = @user.following_users
    @follower_users = @user.follower_users
  end
end

app/controllers/mypage/profiles_controller.rb
class Mypage::ProfilesController < Mypage::BaseController
  before_action :set_user, only: %i[edit update]

  def show
    @user = current_user
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to mypage_profile_path, info: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :name, :icon, :icon_cache)
  end
end

app/helpers/profile/profile_shows_helper.rb
module Profile::ProfileShowsHelper
end

app/helpers/profiles/base_helper.rb
module Profiles::BaseHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/mypage/profiles/_form.html.erb
<%= form_with model: @user, url: mypage_profile_path, local: true, id: "new_icon" do |f| %>
  <div class="mx-2 mt-10 md:flex">
    <div class="px-10 mt-10 mb-8 md:w-1/3">
      <div class="pt-3 form-group">
        <%= image_tag user.icon.url, id: 'preview', size:'250x250',data: { turbo: false }, class:"rounded-full mx-auto" %>
        <div id="previews" class="rounded-full"></div>
        <div class="click-upload">
          <%= f.hidden_field :icon_cache %>
          <%= f.file_field :icon, class: "form-control mt-3" %>
        </div>
      </div>
    </div>
    
    <div class="px-10 pt-6 pb-10 md:mb-10 md:w-2/3">
      <div class="mb-10 form-group">
        <i class="fa-solid fa-user"></i>
        <%= f.label :name, User.human_attribute_name(:name), class:"font-bold text-xl mb-1" %><br>
        <%= f.text_area :name, class: "form-control rounded w-full h-11 focus:ring-gray-500 focus:border-gray-500 mb-5 w-2/5"  %>
      </div>

      <div class="form-group">
        <i class="fa-solid fa-envelope"></i>
        <%= f.label :email, User.human_attribute_name(:email), class:"font-bold text-xl mb-1" %><br>
        <%= f.text_area :email, class: "form-control rounded w-full h-11 focus:ring-gray-500 focus:border-gray-500 mb-5 w-2/5"  %>
      </div>
      
      <div class="mt-20 text-center md:text-end">
        <%= f.submit t('defaults.edit'), class:"bg-green-500 hover:bg-green-600 transition-all duration-300 text-white rounded py-3 px-12 font-bold text-xl cursor-pointer mb-5" %>
      </div>
    </div>
  </div>
<% end %>

app/views/mypage/profiles/edit.html.erb
<% set_meta_tags title: t('.title') %>
<div class="bg-[#f5eace]">
  <%= render 'shared/header' %>
  <div class="container mx-auto">
    <h1 class="secondary-title"><%= t('.title') %></h1>
    <%= render 'form', { user: @user } %>
  </div>
</div>

app/views/mypage/profiles/show.html.erb
<% set_meta_tags title: t('.title') %>
<div class="bg-[#f5eace]">
<%= render 'shared/header' %>
  
  <div class="container mx-auto">
    <h1 class="secondary-title"><%= t('.title') %></h1>
    <div class="mx-2 md:flex">
      <div class="px-10 pb-3 mt-20 mb-8 text-xl font-bold md:w-1/3">
        <p class="third-title">サイドバー</p>
        <ul>
          <li class="mb-3"><%= link_to t('mypage.profiles.show.items_list'), all_items_path %></li>
          
          <li class="mb-3"><%= link_to t('mypage.profiles.show.private_item_list'), private_item_list_items_path %></li>
          
          <li class="mb-3"><%= link_to t('mypage.profiles.show.good'), favorites_user_path(current_user) %></li>
          <li class="mb-3"><%= link_to t('mypage.profiles.show.edit_account'), edit_mypage_profile_path %></li>
        </ul>
      </div>

      <div class="px-10 pb-3 mt-10 text-xl font-bold md:mb-8 md:w-2/3">
        <div class="items-center text-center md:space-x-12 md:flex">
          <div>
            <% if @user && @user.icon? %>
              <%= image_tag @user.icon.url, size:'200x200', class:"rounded-full mx-auto" %>
            <% else %>
              <%= image_tag 'NO_PHOTO.png', size:'200x200', class: "rounded-full mx-auto" %>
            <% end %>
          </div>
          <div>
            <p class="mt-3 mb-3 text-3xl sm:mt-0"><%= current_user.name %></p>
            <%= link_to follows_user_path(@user) do %>
              <p class="mb-1 text-xl"><%= t('mypage.profiles.show.follow') %><%= @user.followers.count %>人</p>
            <% end %>
            <%= link_to followers_user_path(@user) do %>
              <p class="text-xl"><%= t('mypage.profiles.show.follower')%><%= @user.followeds.count %>人</p>
            <% end %>
          </div>
        </div>
        <div class="flex justify-between mt-20 mb-20">
          <div>
            <%= link_to trashed_item_path(@user) do %>
              <p class="mb-5 text-2xl text-center md:mb-2"><%= t('mypage.profiles.show.trash_items') %></p>
              <p class="text-3xl text-center underline"><%= current_user.items.where(reason_status: 'trash').count %>件</p>
            <% end %>
          </div>
          <div>
            <%= link_to stay_item_path(@user) do %>
              <p class="mb-5 text-2xl text-center md:mb-2"><%= t('mypage.profiles.show.stay_items') %></p>
              <p class="text-3xl text-center underline"><%= current_user.items.where(reason_status: 'stay').count %>件</p>
            <% end %>
          </div>
          <div>
            <%= link_to worry_item_path(@user) do %>
              <p class="mb-5 text-2xl text-center md:mb-2"><%= t('mypage.profiles.show.worry_items') %></p>
              <p class="text-3xl text-center underline"><%= current_user.items.where(reason_status: 'worry').count %>件</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>