config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  mount ActionCable.server => '/cable'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: 'auth_at_provider'

  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  resources :contacts, only: %i[new create] do
    collection do
      post 'confirm', to: 'contacts#confirm', as: 'confirm'
      post 'back', to: 'contacts#back', as: 'back'
      get 'done', to: 'contacts#done', as: 'done'
    end
  end

  resources :users, only: %i[new create] do
    member do
      get 'favorites'
      get 'follows', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
    resource :relationships, only: %i[create destroy]
  end

  resources :items do
    resources :comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    get 'trashed', on: :member, to: 'items#trashed_items'
    get 'stay', on: :member, to: 'items#stay_items'
    get 'worry', on: :member, to: 'items#worry_items'
    get 'all', on: :collection, to: 'items#all_items'

    get 'search_tag', to: 'items#search_tag'
    get 'search_genre', to: 'items#search_genre'
    collection do
      get 'search', to: 'items#search', as: :search
    end
    get 'autocomplete', on: :collection, to: 'items#autocomplete'
    get 'private_item_list', on: :collection, to: 'items#private_items'
  end

  namespace :mypage do
    resource :profile, only: %i[show edit update]
    resources :profile_shows, only: %i[show]
  end

  resources :notifications, only: %i[index]

  resources :chat_rooms, only: %i[show create] do
    collection do
      get 'entrance', to: 'chat_rooms#entrance'
    end
  end

  resources :genres, only: %i[new index create]

  resources :password_resets, only: %i[new create edit update]

  get '*path', to: 'application#render404'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/shared/_before_login_header.html.erb
<header class="bg-white">
  <div>
    <div class="relative flex items-center justify-between">
      <div><%= link_to image_tag("logo-header.png", size: '75x75'), root_path, class:"inline" %></div>
      <nav class="container mx-auto text-end">
        
        <button id="button" type="button" class="absolute z-20 mx-auto right-8 top-6">
          <i id="bars" class="md:invisible fa-bars fa-solid fa-2xl"></i>
          <i id="xmark" class="fixed invisible fa-solid fa-x"></i>
        </button>
        
        <ul id="menu" class="fixed top-0 left-0 z-10 w-full py-4 text-center transition ease-linear translate-x-full bg-white md:items-center md:space-x-12 md:translate-x-0 md:flex md:justify-end md:px-4 md:bg-transparent md:static">
          <li class="m-2 md:m-0"><%= link_to items_path, class:"hover:text-lime-800 transition-all duration-300 font-bold text-base" do %>
            <i class="fa-solid fa-gift"></i>
            <%= t('defaults.items') %>
          <% end %></li>
          
          <li class="pb-2 md:pb-0"><%= link_to new_user_path, class:"hover:text-lime-800 transition-all duration-300 font-bold" do %>
            <i class="fa-solid fa-user"></i>
            <%= t('defaults.register')%>
          <% end %></li>
          
          <li class="pb-2 md:pb-0"><%= link_to login_path, class:"hover:text-lime-800 transition-all duration-300 font-bold" do %>
            <i class="fa-solid fa-right-to-bracket"></i>
            <%= t('defaults.login') %>
          <% end %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

<script>
  button.addEventListener('click', event => {
    bars.classList.toggle('invisible');
    xmark.classList.toggle('invisible');
    menu.classList.toggle('translate-x-full');
  })
</script>

app/views/shared/_circle.html.erb
<% if unchecked_notifications.any? %>
  <%= link_to notifications_path, class: "hover:text-lime-800 transition-all duration-300 font-bold text-base" do %>
    <i class="absolute text-[9px] text-red-600 fa-solid fa-circle"></i>
    <i class="fa-solid fa-bell"></i>
    <%= t('defaults.notification') %>
  <% end %>
  <% else %>
    <%= link_to notifications_path, class:"hover:text-lime-800 transition-all duration-300 font-bold text-base" do %>
      <i class="fa-solid fa-bell"></i>
      <%= t('defaults.notification') %>
    <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="m-5 warn">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |message_type, message| %>
    <div class="flash-message <%= message_type %>" role="alert">
      <ul>
        <li><%= message %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-[#5b4744]">
  <div>
    <div class="flex items-center justify-between px-4 md:text-end">
      <%= link_to image_tag("logo-footer.png", size: '75x75'), root_path, class:"inline"%>
      <div class="flex flex-wrap justify-end">
        <%= link_to t('defaults.contact'), new_contact_path, class:"hover:text-lime-800 transition-all duration-300 mr-5 text-white sm:text-base text-sm" %>
        <%= link_to t('defaults.privacy_policy'), privacy_policy_path, class:"hover:text-lime-800 transition-all duration-300 mr-5 text-white sm:text-base text-sm" %>
        <%= link_to t('defaults.terms_of_service'), terms_of_service_path, class: "hover:text-lime-800 transition-all duration-300 text-white sm:text-base text-sm mr-5" %>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-white">
    <div>
      <div class="relative flex items-center justify-between">
        <div><%= link_to image_tag("logo-header.png", size: '75x75'), root_path, class:"inline" %></div>
        <nav>
          <button id="button" type="button" class="absolute z-20 mx-auto right-8 top-6">
            <i id="bars" class="fa-bars fa-solid fa-2xl"></i>
            <i id="xmark" class="fixed invisible fa-solid fa-x"></i>
          </button>
          <div class="mr-20"><%= render 'shared/circle' %></div>
          <ul id="menu" class="fixed top-0 left-0 z-10 w-full text-center transition ease-linear translate-x-full bg-white">
            <li class="p-5 pb-2"><%= link_to items_path, class:"hover:text-lime-800 transition-all duration-300 font-bold text-base" do %>
              <i class="fa-solid fa-gift"></i>
              <%= t('defaults.items') %>
            <% end %></li>

            <li class="pb-2"><%= link_to new_item_path, class:"hover:text-lime-800 transition-all duration-300 font-bold text-base" do %>
              <i class="fa-solid fa-pen"></i>
              <%= t('defaults.items_new') %>
            <% end %></li>
      
            <li class="pb-2"><%= link_to entrance_chat_rooms_path, class:"hover:text-lime-800 transition-all duration-300 font-bold text-base" do %>
              <i class="fa-solid fa-comment"></i>
              <%= t('defaults.chat_rooms') %>
            <% end %></li>

            <li class="pb-3"><%= link_to mypage_profile_path, class:"hover:text-lime-800 transition-all duration-300 font-bold text-base" do %>
              <i class="fa-solid fa-user"></i>
              <%= t('defaults.my_page') %>
            <% end %></li>
          
            <li class="pb-3"><%= link_to logout_path, data: { turbo_method: :delete }, class: "hover:text-lime-800 transition-all duration-300 font-bold text-base" do %>
              <i class="fa-solid fa-right-from-bracket"></i>
              <%= t('defaults.logout') %>
            <% end %></li>
          </ul>
        </nav>
      </div>
    </div>
</header>

<script>
  button.addEventListener('click', event => {
    bars.classList.toggle('invisible');
    xmark.classList.toggle('invisible');
    menu.classList.toggle('translate-x-full');
  })
</script>