config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  mount ActionCable.server => '/cable'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: 'auth_at_provider'

  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  resources :contacts, only: %i[new create] do
    collection do
      post 'confirm', to: 'contacts#confirm', as: 'confirm'
      post 'back', to: 'contacts#back', as: 'back'
      get 'done', to: 'contacts#done', as: 'done'
    end
  end

  resources :users, only: %i[new create] do
    member do
      get 'favorites'
      get 'follows', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
    resource :relationships, only: %i[create destroy]
  end

  resources :items do
    resources :comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    get 'trashed', on: :member, to: 'items#trashed_items'
    get 'stay', on: :member, to: 'items#stay_items'
    get 'worry', on: :member, to: 'items#worry_items'
    get 'all', on: :collection, to: 'items#all_items'

    get 'search_tag', to: 'items#search_tag'
    get 'search_genre', to: 'items#search_genre'
    collection do
      get 'search', to: 'items#search', as: :search
    end
    get 'autocomplete', on: :collection, to: 'items#autocomplete'
    get 'private_item_list', on: :collection, to: 'items#private_items'
  end

  namespace :mypage do
    resource :profile, only: %i[show edit update]
    resources :profile_shows, only: %i[show]
  end

  resources :notifications, only: %i[index]

  resources :chat_rooms, only: %i[show create] do
    collection do
      get 'entrance', to: 'chat_rooms#entrance'
    end
  end

  resources :genres, only: %i[new index create]

  resources :password_resets, only: %i[new create edit update]

  get '*path', to: 'application#render404'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :item_image, ItemImageUploader
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :notifications, dependent: :destroy

  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags

  enum reason_status: { trash: 0, stay: 1, worry: 2 }
  enum status: { published: 0, unpublished: 1 }

  validates :name, presence: true, length: { maximum: 255 }
  validates :item_image, presence: true
  validates :episode_content, presence: true, length: { maximum: 65_535 }
  validates :reason_content, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  belongs_to :genre

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

  def create_notification_favorite(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and item_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    return unless temp.blank?

    notification = current_user.active_notifications.new(item_id: id, visited_id: user_id, action: 'favorite')
    notification.checked = true if notification.visitor_id == notification.visited_id

    notification.save if notification.valid?
  end

  def create_notification_comment(current_user, comment_id, item_id)
    item = Item.find(item_id)
    return unless item && current_user != item.user

    save_notification_comment(current_user, comment_id, item.user.id)
  end

  def save_notification_comment(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(item_id: id, comment_id:, visited_id:, action: 'comment')
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end

  def save_tags(tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(name: new_name)
      self.tags << tag
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[user tags genre]
  end

  def self.ransackable_scopes(auth_object = nil)
    %i[name_or_user_name_or_genre_name_or_tags_name_eq_all]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: %i[index show search autocomplete]
  before_action :set_item, only: %i[edit update destroy]

  def index
    @items = Item.published.includes(:user, :genre, :tags).order(created_at: :desc).page(params[:page]).per(6)
    @tag_list = Tag.all
    @q = Item.ransack(params[:q])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = current_user.items.new(item_params)
    tag_list = params[:item][:tag_list].split(',')
    if @item.save
      @item.save_tags(tag_list)
      redirect_to items_path, info: t('defaults.message.created', item: Item.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_created', item: Item.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @item = Item.find(params[:id])
    @comment = Comment.new(commentable: @item)
    @comments = @item.comments.includes(:user).order(created_at: :desc)
    @tag_list = @item.tags.pluck(:name).join(',')
    @item_tags = @item.tags
    @genre = @item.genre
  end

  def edit
    @tag_list = @item.tags.pluck(:name).join(',')
    @genres = Genre.all
  end

  def update
    tag_list = params[:item][:tag_list].split(',')
    if @item.update(item_params)
      @item.save_tags(tag_list)
      redirect_to items_path, info: t('defaults.message.updated', item: Item.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_updated', item: Item.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy!
    redirect_to items_path, info: t('defaults.message.deleted', item: Item.model_name.human)
  end

  def trashed_items
    @user = User.find(params[:id])
    @trashed_items = Item.where(user_id: current_user.id, reason_status: 'trash').order(created_at: :desc).page(params[:page]).per(6)
    @trashed_items_for_user = Item.where(user_id: params[:id], reason_status: 'trash').order(created_at: :desc).page(params[:page]).per(6)
  end

  def stay_items
    @user = User.find(params[:id])
    @stay_items = Item.where(user_id: current_user.id, reason_status: 'stay').order(created_at: :desc).page(params[:page]).per(6)
    @stay_items_for_user = Item.where(user_id: params[:id], reason_status: 'stay').order(created_at: :desc).page(params[:page]).per(6)
  end

  def worry_items
    @user = User.find(params[:id])
    @worry_items = Item.where(user_id: current_user.id, reason_status: 'worry').order(created_at: :desc).page(params[:page]).per(6)
    @worry_items_for_user = Item.where(user_id: params[:id], reason_status: 'worry').order(created_at: :desc).page(params[:page]).per(6)
  end

  def all_items
    @all_items = current_user.items.order(created_at: :desc).page(params[:page]).per(6)
  end

  def search_tag
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @items = @tag.items.order(created_at: :desc).page(params[:page]).per(6)
  end

  def search_genre
    @genre_list = Genre.all
    @genre = Genre.find(params[:genre_id])
    @items = @genre.items.order(created_at: :desc).page(params[:page]).per(6)
  end

  def search
    @q = Item.ransack(params[:q])
    @search = @q.result(distinct: true)
    @search_results = @search.page(params[:page]).per(6)
  end

  def autocomplete
    @results = []

    items = Item.where("name LIKE ?", "%#{params[:q]}%")
    tags = Tag.where("name LIKE ?", "%#{params[:q]}%")
    genres = Genre.where("name LIKE ?", "%#{params[:q]}%")
    users = User.where("name LIKE ?", "%#{params[:q]}%")

    item_names = items.pluck(:name)
    tag_names = tags.pluck(:name)
    genre_names = genres.pluck(:name)
    user_names = users.pluck(:name)

    @results = (item_names + tag_names + genre_names + user_names).uniq

    respond_to(&:js)
  end

  def private_items
    @private_items = current_user.items.unpublished.order(created_at: :desc).page(params[:page]).per(6)
  end

  private

  def set_item
    @item = current_user.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :episode_content, :reason_content, :item_image, :item_image_cache, :reason_status, :status, :genre_id, tag_list: [])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with model: item, local: true, id: "new_item" do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
    <div class="md:flex">
      <div class="px-10 mb-8 md:w-1/2">
        <div class="form-group">
          <%= f.label :name, Item.human_attribute_name(:name) %>
          <%= f.text_field :name, class: "form-control w-3/5", id: "item_name", placeholder: "カバン" %>
        </div>
        <div class="pt-3 form-group">
          <%= image_tag item.item_image.url, id: 'preview', size:'400x400', data: { turbo: false } %>
          <div id="previews"></div>
          <div class="click-upload">
            <%= f.hidden_field :item_image_cache %>
            <%= f.file_field :item_image, class: "form-control mt-3 w-full" %>
          </div>
        </div>
      </div>
      
      <div class="px-10 pb-5 md:w-1/2">
        <div class="form-group">
          <%= f.label :episode_content, Item.human_attribute_name(:episode_content) %>
          <%= f.text_area :episode_content, class:"form-control h-24 w-full", id:"item_episode_content", placeholder: "家族との旅行で持っていきました" %>
        </div>
        
        <div class="form-group">
          <%= f.radio_button :reason_status, :trash, id: "item_reason_status" %>
          <%= f.label :reason_status, t('enums.item.reason_status.trash'), id: "item_reason_status" %>
          <%= f.radio_button :reason_status, :stay %>
          <%= f.label :reason_status, t('enums.item.reason_status.stay') %>
          <%= f.radio_button :reason_status, :worry %>
          <%= f.label :reason_status, t('enums.item.reason_status.worry') %>
          <span>理由</span>
          <%= f.text_area :reason_content, class:"form-control h-24 w-full", placeholder: "古くなったから捨てます" %>
        </div>

        <div class="form-group">
          <%= f.label :tag_list, Tag.human_attribute_name(:name) %><br>
          <%= f.text_field :tag_list, value: @tag_list, class: "form-control w-full", placeholder: ',で区切ると複数のタグが登録できます' %>
        </div>
        
        <div class="pt-1 form-group">
          <%= f.label :name, Genre.human_attribute_name(:name) %>
          <div><%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: '選択してください' }, class: 'form-control w-full' %></div>
        </div>
        
        <div class="pt-1 form-group">
          <%= f.radio_button :status, :published, id: "item_status" %>
          <%= f.label :status, t('enums.item.status.published'), id: "item_status" %>
          <%= f.radio_button :status, :unpublished %>
          <%= f.label :status, t('enums.item.status.unpublished') %>
        </div>
          
        <div class="mt-8 text-center md:text-end">
          <%= f.submit t('defaults.submission'), class:"bg-green-500 hover:bg-green-600 transition-all duration-300 text-white rounded py-3 px-12 font-bold text-xl cursor-pointer " %>
        </div>
      </div>
    </div>
<% end %>

app/views/items/_item.html.erb
<div class="mb-5">
  <ul class="p-5 border-4 border-[#5b4744] border-dashed rounded-3xl shadow-xl bg-[#eee5bc] w-[330px] h-[560px]">
    <%= link_to item_path(item) do %>
    <li><%= image_tag item.item_image.url, size: '300x300', class:"pb-3 mx-auto" %></li>
    <% end %>
    <%= link_to item_path(item) do %>
      <li class="pb-1 text-xl font-bold"><%= item.name %></li>
    <% end %>
    <% if logged_in? %>
      <% if current_user.own?(item) %>
        <%= link_to mypage_profile_path do %>
          <p class="mb-2 text-xl font-bold">by：<%= item.user.name %></p>
        <% end %>
      <% else %>
        <%= link_to mypage_profile_show_path(item.user) do %>
          <p class="mb-2 text-xl font-bold">by：<%= item.user.name %></p>
        <% end %>
      <% end %>
    <% else %>
      <p class="mb-2 text-xl font-bold">by：<%= item.user.name %></p>
    <% end %>
      <li>
        <span class="mb-2 text-xl font-bold"><%= t('defaults.tag') %></span>
        <% item.tags.each do |tag| %>
          <%= link_to tag.name, item_search_tag_path(item_id: item.id, tag_id: tag.id), class: 'font-bold text-xl' %>
          <%="(#{tag.items.count})" %>
        <% end %>
      </li>
      <li class="pb-1 text-xl font-bold">
        <% if item.genre %>
          <%= link_to item_search_genre_path(item_id: item.id, genre_id: item.genre.id) do %>
            <%= t('defaults.genres') %><%= item.genre.name %></li>
          <% end %>
        <% end %>
      </li>
      <li><p class="text-xl font-bold">
          <%= link_to item_path(item) do %>
            <%= item.reason_status_i18n %><%= t('defaults.reason') %></p>
            <p class="text-lg line-clamp-2"><%= item.reason_content %></p>
          <% end %>
      </li>
  </ul>
</div>

app/views/items/all_items.html.erb
<% set_meta_tags title: t('.title') %>
<div class="bg-[#f5eace] grow">
<%= render 'shared/header' %>
  <div>
    <div class="container mx-auto">
      <h1 class="secondary-title"><%= t('.title') %></h1>
      <div class="grid grid-cols-1 gap-10 lg:grid-cols-3 md:grid-cols-2 auto-rows-auto place-content-center place-items-center">
        <% if @all_items.present? %>
          <%= render @all_items %>
        <% else %>
          <p><%= t('.no_result') %><br>思い出の品物を投稿しましょう！</p>
        <% end %>
      </div>
      <%= paginate @all_items %>
    </div>
  </div>
</div>

app/views/items/autocomplete.html.erb
<% @results.each do |result| %>
  <li class="w-80 flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-green-200 focus:ring-2 focus:ring-green-800 dark:text-gray-400 dark:hover:bg-blue-200 dark:hover:text-gray-300" role="option">
    <%= result.is_a?(Hash) ? result[:name] : result.respond_to?(:name) ? result.name : result %>
  </li>
<% end %>

app/views/items/edit.html.erb
<div class="bg-[#f5eace]">
  <%= render 'shared/header' %>
  <div class="container mx-auto">
    <h1 class="secondary-title"><%= t('.title') %></h1>
    <%= render 'form', { item: @item } %>
  </div>
</div>

app/views/items/index.html.erb
<% set_meta_tags title: t('.title') %>
<div class="bg-[#f5eace] grow">
<% if logged_in? %>
  <%= render 'shared/header' %>
<% else %>
  <%= render 'shared/before_login_header' %>
<% end %>
  <div>
    <div class="container mx-auto">
      <h1 class="secondary-title"><%= t('.title') %></h1>
      <div class="relative mx-10 md:mx-auto">
        <%= search_form_for @q, url: search_items_path do |f| %>
          <div data-controller="autocomplete" data-autocomplete-url-value="/items/autocomplete" role="combobox">
            <%= f.search_field :name_or_user_name_or_genre_name_or_tags_name_eq, data: { autocomplete_target: 'input' }, id:"search_field", placeholder: "品物名、ユーザー名、ジャンル、タグ", class: "block w-full p-4 md:px-10 text-sm text-gray-900 rounded-lg bg-gray-50 focus:ring-gray-500 focus:border-gray-500 placeholder:opacity-0 placeholder:md:opacity-100" %>
            <ul class="absolute w-full bg-white list-group md:text-sm max-w-max" data-autocomplete-target="results"></ul>
              <svg class="absolute w-4 h-4 transform -translate-y-1/2 right-4 top-7" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
              </svg>
            <%= f.submit "", class: "absolute top-0 right-0 h-full p-4 text-sm font-medium rounded-r-lg text-gray focus:ring-4 focus:outline-none cursor-pointer" %>
          </div>
        <% end %>
      </div>
      <div class="mx-10 mt-2 mb-6 md:mx-auto">
        <p>→品物投稿フォームは<%= link_to "こちら", new_item_path, class: "underline font-bold hover:text-lime-800" %></p>
      </div>
      <div class="grid grid-cols-1 gap-10 lg:grid-cols-3 md:grid-cols-2 auto-rows-auto place-content-center place-items-center">
        <% if @items.present? %>
          <%= render @items %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<% set_meta_tags title: t('.title') %>
<div class="bg-[#f5eace]">
  <%= render 'shared/header' %>
  <div class="container mx-auto">
    <h1 class="secondary-title"><%= t('.title') %></h1>
    <%= render 'form', { item: @item } %>
  </div>
</div>

app/views/items/search.html.erb
<% set_meta_tags title: t('.title') %>
<div class="bg-[#f5eace] grow">
<% if logged_in? %>
  <%= render 'shared/header' %>
<% else %>
  <%= render 'shared/before_login_header' %>
<% end %>
  <div>
    <div class="container mx-auto">
      <h1 class="secondary-title"><%= t('.title') %></h1>
      <div class="grid grid-cols-1 gap-10 lg:grid-cols-3 md:grid-cols-2 auto-rows-auto place-content-center place-items-center">
        <% if  @search_results.present? %>
          <%= render @search_results %>
        <% else %>
          <p><%= t('.no_result') %><br>
          <%= link_to "他の人の投稿", items_path, class: "underline pointer text-xl font-bold"%>を見てみましょう！</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/search_genre.html.erb
<div class="bg-[#f5eace]">
<%= render 'shared/header' %>
  <div>
    <div class="container mx-auto">
      <h1 class="secondary-title"><%= t('.title') %></h1>
      <div class="grid grid-cols-1 gap-10 lg:grid-cols-3 md:grid-cols-2 auto-rows-auto place-content-center place-items-center">
        <% if  @items.present? %>
          <%= render  @items %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/items/search_tag.html.erb
<div class="bg-[#f5eace]">
<%= render 'shared/header' %>
  <div>
    <div class="container mx-auto">
      <h1 class="secondary-title"><%= t('.title') %></h1>
      <div class="grid grid-cols-1 gap-10 lg:grid-cols-3 md:grid-cols-2 auto-rows-auto place-content-center place-items-center">
        <% if  @items.present? %>
          <%= render  @items %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<% set_meta_tags title: t('.title') %>
<div class="bg-[#f5eace] grow">
<% if logged_in? %>
  <%= render 'shared/header' %>
<% else %>
  <%= render 'shared/before_login_header' %>
<% end %>
  <div class="container mx-auto">
    <h1 class="secondary-title"><%= t('.title') %></h1>
  
    <div class="md:flex">
      <div class="px-10 pb-3 mb-8 text-xl font-bold md:w-1/2">
        <%= @item.name %><br>
        <% if logged_in? %>
          <% if current_user.own?(@item) %>
            <%= link_to mypage_profile_path do %>
              <p class="mt-2">by：<%= @item.user.name %></p>
            <% end %>
          <% else %>
            <%= link_to mypage_profile_show_path(@item.user) do %>
              <p class="mt-2">by：<%= @item.user.name %></p>
            <% end %>
          <% end %>
        <% else %>
          <p class="mt-2">by：<%= @item.user.name %></p>
        <% end %>
        
        <%= image_tag @item.item_image.url, size:'400x400', class:"mt-4 sm:mx-auto" %>
      </div>
      <div class="px-10 pb-11 md:w-1/2">
        <div>
          <% if logged_in? %>
            <% if @item.favorited?(current_user) %>
              <%= link_to item_favorites_path(@item.id), data: { turbo_method: :delete }, class: 'flex items-baseline justify-end' do %>
                <p class="text-rose-600"><%= t('items.show.good') %></p>
                <i class="fa-solid fa-thumbs-up fa-lg" style="color: #d90d0d;"></i>
              <% end %>
            <% else %>
              <%= link_to item_favorites_path(@item.id), data: { turbo_method: :post }, class: 'flex items-baseline justify-end' do %>
                <p><%= t('items.show.good') %></p>
                <i class="fa-solid fa-thumbs-up fa-lg"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="mb-5">
          <p class="text-xl font-bold"><%= t('items.show.episode_content') %></p>
          <%= @item.episode_content %>
        </div>
        <div class="mb-5">
          <p class="text-xl font-bold"><%= @item.reason_status_i18n %><%= t('items.show.reason') %></p>
          <%= @item.reason_content %>
        </div>
        <div class="mb-5">
          <p class="text-xl font-bold"><%= t('items.show.tag') %></p>
            <% @item_tags.each do |tag| %>
              <%= link_to tag.name, item_search_tag_path(item_id: @item.id, tag_id: tag.id) %>
            <% end %>
        </div>
        
        <% if @genre %>
          <div class="mb-5">
            <p class="text-xl font-bold"><%= t('items.show.genre') %></p>
            <%= link_to @genre.name, item_search_genre_path(item_id: @item.id, genre_id: @genre.id) %>
          </div>
        <% end %>
        
        <% if logged_in? %>
          <% if current_user.own?(@item) %>
            <div class="flex justify-end space-x-5">
              <%= link_to t('defaults.edit'), edit_item_path, class: "px-5 py-2 text-xl font-bold text-white transition-all duration-300 bg-yellow-500 rounded cursor-pointer hover:bg-yellow-600", id: "item-#{@item.id}" %>
              <%= link_to t('defaults.destroy'), item_path, data: { turbo_method: :delete }, class:"px-5 py-2 text-xl font-bold text-white transition-all duration-300 bg-red-500 rounded cursor-pointer hover:bg-red-600", id: "item-#{@item.id}" %>
            </div>
          <% end %>
        <% end %>
        <% if logged_in? %>
          <div>
            <%= render 'comments/comments', { comments: @comments } %>
          </div>
          <div>
            <%= render 'comments/form', { item: @item, comment: @comment } %>
          </div>
        <% end %>
      </div> 
    </div>
  </div>  
</div>

app/views/items/stay_items.html.erb
<% set_meta_tags title: t('.title') %>
<div class="bg-[#f5eace] grow">
<%= render 'shared/header' %>
  <div>
    <div class="container mx-auto">
      <h1 class="secondary-title"><%= t('.title') %></h1>
      <div class="grid grid-cols-1 gap-10 lg:grid-cols-3 md:grid-cols-2 auto-rows-auto place-content-center place-items-center">
        <% if current_user.id == @user.id %>
          <% if @stay_items.present? %>
            <%= render @stay_items %>
          <% else %>
            <p><%= t('.no_result') %></p>
          <% end %>
        <% else %>
          <% if @stay_items_for_user.present? %>
            <%= render @stay_items_for_user %>
          <% else %>
            <p><%= t('.no_result') %></p>
          <% end %>
        <% end %>
      </div>
      <% if current_user.id == @user.id %>
        <% if @stay_items.present? %>
          <%= paginate @stay_items %>
        <% end %>
      <% else %>
        <% if @stay_items_for_user.present? %>
          <%= paginate @stay_items_for_user %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/trashed_items.html.erb
<% set_meta_tags title: t('.title') %>
<div class="bg-[#f5eace] grow">
<%= render 'shared/header' %>
  <div>
    <div class="container mx-auto">
      <h1 class="secondary-title"><%= t('.title') %></h1>
      <div class="grid grid-cols-1 gap-10 lg:grid-cols-3 md:grid-cols-2 auto-rows-auto place-content-center place-items-center">
        <% if current_user.id == @user.id %>
          <% if @trashed_items.present? %>
            <%= render @trashed_items %>
          <% else %>
            <p><%= t('.no_result') %></p>
          <% end %>
        <% else %>
          <% if @trashed_items_for_user.present? %>
            <%= render @trashed_items_for_user %>
          <% else %>
            <p><%= t('.no_result') %></p>
          <% end %>
        <% end %>
      </div>
      <% if current_user.id == @user.id %>
        <% if @trashed_items.present? %>
          <%= paginate @trashed_items %>
        <% end %>
      <% else %>
        <% if @trashed_items_for_user.present? %>
          <%= paginate @trashed_items_for_user %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/worry_items.html.erb
<% set_meta_tags title: t('.title') %>
<div class="bg-[#f5eace] grow">
<%= render 'shared/header' %>
  <div>
    <div class="container mx-auto">
      <h1 class="secondary-title"><%= t('.title') %></h1>
      <div class="grid grid-cols-1 gap-10 lg:grid-cols-3 md:grid-cols-2 auto-rows-auto place-content-center place-items-center">
        <% if current_user.id == @user.id %>
          <% if @worry_items.present? %>
            <%= render @worry_items %>
          <% else %>
            <p><%= t('.no_result') %></p>
          <% end %>
        <% else %>
          <% if @worry_items_for_user.present? %>
            <%= render @worry_items_for_user %>
          <% else %>
            <p><%= t('.no_result') %></p>
          <% end %>
        <% end %>
      </div>
      <% if current_user.id == @user.id %>
        <% if @worry_items.present? %>
          <%= paginate @worry_items %>
        <% end %>
      <% else %>
        <% if @worry_items_for_user.present? %>
          <%= paginate @worry_items_for_user %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>