config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  mount ActionCable.server => '/cable'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: 'auth_at_provider'

  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  resources :contacts, only: %i[new create] do
    collection do
      post 'confirm', to: 'contacts#confirm', as: 'confirm'
      post 'back', to: 'contacts#back', as: 'back'
      get 'done', to: 'contacts#done', as: 'done'
    end
  end

  resources :users, only: %i[new create] do
    member do
      get 'favorites'
      get 'follows', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
    resource :relationships, only: %i[create destroy]
  end

  resources :items do
    resources :comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    get 'trashed', on: :member, to: 'items#trashed_items'
    get 'stay', on: :member, to: 'items#stay_items'
    get 'worry', on: :member, to: 'items#worry_items'
    get 'all', on: :collection, to: 'items#all_items'

    get 'search_tag', to: 'items#search_tag'
    get 'search_genre', to: 'items#search_genre'
    collection do
      get 'search', to: 'items#search', as: :search
    end
    get 'autocomplete', on: :collection, to: 'items#autocomplete'
    get 'private_item_list', on: :collection, to: 'items#private_items'
  end

  namespace :mypage do
    resource :profile, only: %i[show edit update]
    resources :profile_shows, only: %i[show]
  end

  resources :notifications, only: %i[index]

  resources :chat_rooms, only: %i[show create] do
    collection do
      get 'entrance', to: 'chat_rooms#entrance'
    end
  end

  resources :genres, only: %i[new index create]

  resources :password_resets, only: %i[new create edit update]

  get '*path', to: 'application#render404'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/mypage/base_controller.rb
class Mypage::BaseController < ApplicationController
  layout 'mypage/layouts/application'
  before_action :require_login
end

app/controllers/mypage/profile_shows_controller.rb
class Mypage::ProfileShowsController < Mypage::BaseController
  def show
    @user = User.find(params[:id])
    @following_users = @user.following_users
    @follower_users = @user.follower_users
  end
end

app/controllers/mypage/profiles_controller.rb
class Mypage::ProfilesController < Mypage::BaseController
  before_action :set_user, only: %i[edit update]

  def show
    @user = current_user
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to mypage_profile_path, info: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :name, :icon, :icon_cache)
  end
end

app/helpers/profile/profile_shows_helper.rb
module Profile::ProfileShowsHelper
end

app/views/mypage/profile_shows/show.html.erb
<% set_meta_tags title: @user.name %>
<div class="bg-[#f5eace]">
<%= render 'shared/header' %>
  <div class="container mx-auto">
    <h1 class="secondary-title"><%= @user.name %>さんのページ</h1>
    <div class="mx-2">
      
      <div class="px-10 pb-3 mt-10 text-xl font-bold md:pb-8">
        <div class="mb-10 text-center sm:text-end">
          <% if current_user != @user %>
            <% if current_user.following?(@user) %>
              <%= link_to t('defaults.unfollow'), user_relationships_path(@user.id), data: { turbo_method: :delete }, class: 'bg-green-500 hover:bg-green-600 transition-all duration-300 text-white rounded py-3 px-12 font-bold text-xl cursor-pointer text-end' %>
            <% else %>
              <%= link_to t('defaults.follow'), user_relationships_path(@user.id), data: { turbo_method: :post }, class: 'bg-green-500 hover:bg-green-600 transition-all duration-300 text-white rounded py-3 px-12 font-bold text-xl cursor-pointer' %>
            <% end %>
          <% end %>
        </div>
        <div class="items-center justify-center text-center md:space-x-12 md:flex">
          <div>
            <% if @user && @user.icon? %>
              <%= image_tag @user.icon.url, size:'200x200', class:"rounded-full mx-auto" %>
            <% else %>
              <%= image_tag 'NO_PHOTO.png', size:'200x200', class: "rounded-full mx-auto" %>
            <% end %>
          </div>
          <div>
            <p class="mt-3 mb-3 text-3xl sm:mt-0"><%= @user.name %></p>
            <%= link_to follows_user_path(@user) do %>
              <p class="mb-1 text-xl"><%= t('mypage.profiles.show.follow') %><%= @user.followers.count %>人</p>
            <% end %>
            <%= link_to followers_user_path(@user) do %>
              <p class="text-xl"><%= t('mypage.profiles.show.follower')%><%= @user.followeds.count %>人</p>
            <% end %>
          </div>
          
        </div>
        <div class="flex justify-center mt-20 mb-10 space-x-12">
          <div>
            <%= link_to trashed_item_path do %>
              <p class="mb-5 text-2xl text-center md:mb-2"><%= t('mypage.profiles.show.trash_items') %></p>
              <p class="text-3xl text-center underline"><%= @user.items.where(reason_status: 'trash').count %>件</p>
            <% end %>
          </div>
          <div>
            <%= link_to stay_item_path do %>
              <p class="mb-5 text-2xl text-center md:mb-2"><%= t('mypage.profiles.show.stay_items') %></p>
              <p class="text-3xl text-center underline"><%= @user.items.where(reason_status: 'stay').count %>件</p>
            <% end %>
          </div>
          <div>
            <%= link_to worry_item_path do %>
              <p class="mb-5 text-2xl text-center md:mb-2"><%= t('mypage.profiles.show.worry_items') %></p>
              <p class="text-3xl text-center underline"><%= @user.items.where(reason_status: 'worry').count %>件</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>